# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

axisepmgp <- function(m, K, lb, ub) {
    .Call(`_epmgpr_axisepmgp`, m, K, lb, ub)
}

didactic_axisepmgp <- function(m, K, lb, ub, max_steps) {
    .Call(`_epmgpr_didactic_axisepmgp`, m, K, lb, ub, max_steps)
}

didactic_epmgp <- function(m, K, C, lb, ub, max_steps) {
    .Call(`_epmgpr_didactic_epmgp`, m, K, C, lb, ub, max_steps)
}

epmgp <- function(m, K, C, lb, ub, max_steps) {
    .Call(`_epmgpr_epmgp`, m, K, C, lb, ub, max_steps)
}

sample_epmh <- function(n_samples, ep_mean, ep_chol, F, g, initial) {
    .Call(`_epmgpr_sample_epmh`, n_samples, ep_mean, ep_chol, F, g, initial)
}

range_intersection <- function(first, second) {
    .Call(`_epmgpr_range_intersection`, first, second)
}

sample_epess <- function(n_samples, ep_mean, ep_chol, F, g, J, N, initial, verbose) {
    .Call(`_epmgpr_sample_epess`, n_samples, ep_mean, ep_chol, F, g, J, N, initial, verbose)
}

test_wall_hit <- function(nu, initial, ep_mean, ep_chol, F, g, J, N) {
    .Call(`_epmgpr_test_wall_hit`, nu, initial, ep_mean, ep_chol, F, g, J, N)
}

erfcx <- function(x) {
    .Call(`_epmgpr_erfcx`, x)
}

trunc_norm_moments <- function(lb_in, ub_in, mu_in, sigma_in) {
    .Call(`_epmgpr_trunc_norm_moments`, lb_in, ub_in, mu_in, sigma_in)
}

